# Generated by Django 4.2.7 on 2023-12-19 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('Data_id', models.AutoField(primary_key=True, serialize=False)),
                ('Image', models.ImageField(upload_to='media/')),
            ],
            options={
                'db_table': 'upload',
            },
        ),
        migrations.CreateModel(
            name='Last_login',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Login_Time', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'last_login',
            },
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('Username', models.TextField(max_length=30, null=True)),
                ('Email_id', models.EmailField(max_length=30, null=True)),
                ('Image', models.FileField(null=True, upload_to='images/')),
                ('Age', models.IntegerField(null=True)),
                ('Contact', models.TextField(max_length='30', null=True)),
                ('Password', models.TextField(max_length=30, null=True)),
                ('Date_time', models.DateTimeField(auto_now=True, null=True)),
                ('user_status', models.TextField(default='pending', max_length=30, null=True)),
                ('user_feedback', models.TextField(max_length=1000, null=True)),
                ('otp', models.IntegerField(null=True)),
                ('Otp_Status', models.TextField(default='pending', max_length=60, null=True)),
                ('Last_Login_Time', models.TimeField(auto_now_add=True, null=True)),
                ('Last_Login_Date', models.DateField(auto_now_add=True, null=True)),
                ('No_Of_Times_Login', models.IntegerField(default=0, null=True)),
                ('Message', models.TextField(max_length=250, null=True)),
            ],
            options={
                'db_table': 'fire_detection_table',
            },
        ),
        migrations.CreateModel(
            name='UserFeedbackModels',
            fields=[
                ('feed_id', models.AutoField(primary_key=True, serialize=False)),
                ('star_feedback', models.TextField(max_length=900)),
                ('star_rating', models.IntegerField()),
                ('star_Date', models.DateTimeField(auto_now_add=True, null=True)),
                ('sentment', models.TextField(max_length=20, null=True)),
                ('user_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.userdetails')),
            ],
            options={
                'db_table': 'feedback_table',
            },
        ),
    ]
